language: rust
cache: cargo
script:
    - cargo test
    - cargo test --features=stats
    - cargo test --features=debug
rust:
    - stable
    - nightly
matrix:
    allow_failures:
        - rust: stable
